Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\PreprocessingCode.py 
Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\PreprocessingCode.py", line 21, in <module>
    _,contours, hierarchy = cv2.findContours(th2,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
>>> 
 RESTART: C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\PreprocessingCode.py 
Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\PreprocessingCode.py", line 21, in <module>
    contours, hierarchy = cv2.findContours(th2,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
TypeError: Expected Ptr<cv::UMat> for argument 'image'
>>> 
 RESTART: C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\PreprocessingCode.py 
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\100_left.jpeg
1
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\100_right.jpeg
2
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\102_left.jpeg
3
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\102_right.jpeg
4
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\104_left.jpeg
5
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\104_right.jpeg
6
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\108_left.jpeg
7
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\108_right.jpeg
8
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\10_left.jpeg
9
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\10_right.jpeg
10
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\111_left.jpeg
11
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\111_right.jpeg
12
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\114_left.jpeg
13
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\114_right.jpeg
14
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\115_left.jpeg
15
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\115_right.jpeg
16
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\117_left.jpeg
17
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\117_right.jpeg
18
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\119_left.jpeg
19
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\119_right.jpeg
20
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\122_left.jpeg
21
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\122_right.jpeg
22
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\125_left.jpeg
23
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\125_right.jpeg
24
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\129_left.jpeg
25
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\129_right.jpeg
26
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\13_left.jpeg
27
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\13_right.jpeg
28
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\140_left.jpeg
29
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\140_right.jpeg
30
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\145_left.jpeg
31
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\145_right.jpeg
32
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\149_left.jpeg
33
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\149_right.jpeg
34
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\155_left.jpeg
35
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\155_right.jpeg
36
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\156_left.jpeg
37
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\156_right.jpeg
38
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\157_left.jpeg
39
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\157_right.jpeg
40
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\159_left.jpeg
41
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\159_right.jpeg
42
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\15_left.jpeg
43
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\15_right.jpeg
44
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\161_left.jpeg
45
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\161_right.jpeg
46
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\162_left.jpeg
47
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\162_right.jpeg
48
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\163_left.jpeg
49
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\163_right.jpeg
50
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\164_left.jpeg
51
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\164_right.jpeg
52
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\167_left.jpeg
53
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\167_right.jpeg
54
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\169_left.jpeg
55
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\169_right.jpeg
56
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\16_left.jpeg
57
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\16_right.jpeg
58
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\170_left.jpeg
59
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\170_right.jpeg
60
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\172_left.jpeg
61
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\172_right.jpeg
62
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\174_left.jpeg
63
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\174_right.jpeg
64
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\177_left.jpeg
65
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\177_right.jpeg
66
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\178_left.jpeg
67
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\178_right.jpeg
68
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\179_left.jpeg
69
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\179_right.jpeg
70
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\17_left.jpeg
71
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\17_right.jpeg
72
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\184_left.jpeg
73
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\184_right.jpeg
74
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\186_left.jpeg
75
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\186_right.jpeg
76
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\190_left.jpeg
77
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\190_right.jpeg
78
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\192_left.jpeg
79
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\192_right.jpeg
80
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\194_left.jpeg
81
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\194_right.jpeg
82
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\195_left.jpeg
83
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\195_right.jpeg
84
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\197_left.jpeg
85
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\197_right.jpeg
86
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\199_left.jpeg
87
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\199_right.jpeg
88
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\19_left.jpeg
89
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\19_right.jpeg
90
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\203_left.jpeg
91
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\203_right.jpeg
92
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\204_left.jpeg
93
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\204_right.jpeg
94
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\208_left.jpeg
95
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\208_right.jpeg
96
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\20_left.jpeg
97
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\20_right.jpeg
98
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\210_left.jpeg
99
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\210_right.jpeg
100
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\211_left.jpeg
101
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\211_right.jpeg
102
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\214_left.jpeg
103
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\214_right.jpeg
104
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\216_left.jpeg
105
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\216_right.jpeg
106
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\217_left.jpeg
107
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\217_right.jpeg
108
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\218_left.jpeg
109
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\218_right.jpeg
110
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\219_left.jpeg
111
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\219_right.jpeg
112
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\21_left.jpeg
113
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\21_right.jpeg
114
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\222_left.jpeg
115
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\222_right.jpeg
116
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\224_left.jpeg
117
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\224_right.jpeg
118
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\225_left.jpeg
119
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\225_right.jpeg
120
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\227_left.jpeg
121
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\227_right.jpeg
122
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\229_left.jpeg
123
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\229_right.jpeg
124
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\22_left.jpeg
125
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\22_right.jpeg
126
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\231_left.jpeg
127
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\231_right.jpeg
128
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\232_left.jpeg
129
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\232_right.jpeg
130
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\234_left.jpeg
131
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\234_right.jpeg
132
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\236_left.jpeg
133
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\236_right.jpeg
134
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\239_left.jpeg
135
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\239_right.jpeg
136
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\23_left.jpeg
137
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\23_right.jpeg
138
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\240_left.jpeg
139
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\240_right.jpeg
140
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\241_left.jpeg
141
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\241_right.jpeg
142
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\242_left.jpeg
143
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\242_right.jpeg
144
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\244_left.jpeg
145
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\244_right.jpeg
146
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\249_left.jpeg
147
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\249_right.jpeg
148
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\252_left.jpeg
149
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\252_right.jpeg
150
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\256_left.jpeg
151
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\256_right.jpeg
152
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\257_left.jpeg
153
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\257_right.jpeg
154
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\258_left.jpeg
155
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\258_right.jpeg
156
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\259_left.jpeg
157
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\259_right.jpeg
158
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\25_left.jpeg
159
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\25_right.jpeg
160
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\260_left.jpeg
161
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\260_right.jpeg
162
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\263_left.jpeg
163
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\263_right.jpeg
164
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\264_left.jpeg
165
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\264_right.jpeg
166
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\274_left.jpeg
167
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\274_right.jpeg
168
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\277_left.jpeg
169
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\277_right.jpeg
170
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\279_left.jpeg
171
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\279_right.jpeg
172
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\280_left.jpeg
173
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\280_right.jpeg
174
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\283_left.jpeg
175
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\283_right.jpeg
176
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\286_left.jpeg
177
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\286_right.jpeg
178
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\288_left.jpeg
179
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\288_right.jpeg
180
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\289_left.jpeg
181
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\289_right.jpeg
182
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\294_left.jpeg
183
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\294_right.jpeg
184
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\299_left.jpeg
185
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\299_right.jpeg
186
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\301_left.jpeg
187
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\301_right.jpeg
188
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\307_left.jpeg
189
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\307_right.jpeg
190
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\30_left.jpeg
191
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\30_right.jpeg
192
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\310_left.jpeg
193
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\310_right.jpeg
194
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\311_left.jpeg
195
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\311_right.jpeg
196
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\314_left.jpeg
197
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\314_right.jpeg
198
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\316_left.jpeg
199
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\316_right.jpeg
200
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\317_left.jpeg
201
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\317_right.jpeg
202
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\318_left.jpeg
203
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\318_right.jpeg
204
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\31_left.jpeg
205
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\31_right.jpeg
206
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\320_left.jpeg
207
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\320_right.jpeg
208
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\322_left.jpeg
209
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\322_right.jpeg
210
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\323_left.jpeg
211
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\323_right.jpeg
212
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\325_left.jpeg
213
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\325_right.jpeg
214
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\326_left.jpeg
215
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\326_right.jpeg
216
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\328_left.jpeg
217
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\328_right.jpeg
218
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\329_left.jpeg
219
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\329_right.jpeg
220
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\330_left.jpeg
221
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\330_right.jpeg
222
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\333_left.jpeg
223
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\333_right.jpeg
224
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\337_left.jpeg
225
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\337_right.jpeg
226
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\338_left.jpeg
227
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\338_right.jpeg
228
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\33_left.jpeg
229
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\33_right.jpeg
230
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\343_left.jpeg
231
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\343_right.jpeg
232
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\348_left.jpeg
233
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\348_right.jpeg
234
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\349_left.jpeg
235
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\349_right.jpeg
236
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\36_left.jpeg
237
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\36_right.jpeg
238
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\40_left.jpeg
239
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\40_right.jpeg
240
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\41_left.jpeg
241
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\41_right.jpeg
242
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\42_left.jpeg
243
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\42_right.jpeg
244
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\46_left.jpeg
245
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\46_right.jpeg
246
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\47_left.jpeg
247
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\47_right.jpeg
248
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\49_left.jpeg
249
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\49_right.jpeg
250
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\51_left.jpeg
251
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\51_right.jpeg
252
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\52_left.jpeg
253
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\52_right.jpeg
254
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\54_left.jpeg
255
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\54_right.jpeg
256
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\56_left.jpeg
257
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\56_right.jpeg
258
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\57_left.jpeg
259
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\57_right.jpeg
260
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\58_left.jpeg
261
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\58_right.jpeg
262
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\59_left.jpeg
263
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\59_right.jpeg
264
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\60_left.jpeg
265
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\60_right.jpeg
266
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\62_left.jpeg
267
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\62_right.jpeg
268
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\64_left.jpeg
269
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\64_right.jpeg
270
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\65_left.jpeg
271
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\65_right.jpeg
272
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\66_left.jpeg
273
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\66_right.jpeg
274
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\67_left.jpeg
275
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\67_right.jpeg
276
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\70_left.jpeg
277
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\70_right.jpeg
278
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\72_left.jpeg
279
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\72_right.jpeg
280
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\73_left.jpeg
281
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\73_right.jpeg
282
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\74_left.jpeg
283
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\74_right.jpeg
284
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\75_left.jpeg
285
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\75_right.jpeg
286
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\78_left.jpeg
287
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\78_right.jpeg
288
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\79_left.jpeg
289
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\79_right.jpeg
290
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\81_left.jpeg
291
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\81_right.jpeg
292
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\82_left.jpeg
293
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\82_right.jpeg
294
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\84_left.jpeg
295
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\84_right.jpeg
296
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\95_left.jpeg
297
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\95_right.jpeg
298
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\99_left.jpeg
299
C:\Users\ADMIN\Desktop\Diabetic_Retinopathy_Detection-master\Diabetic_Retinopathy_Detection-master\data\train\99_right.jpeg
300
>>> 
